[package]
name = "kern"
version = "0.1.0"
authors = ["Lukas Buchli <lbu01@buchli-bigger.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peg = "0.6.0"
